### ISSUE TITLE
[GEMM] Fix functional issues with non-float16 dtype

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1097]
`09-experimental-block-pointer.py` tutorial is implemented for GEMM float16 dtype.
It can be executed as `TRITON_INTEL_ENABLE_BLOCK_PTR=1 python 09-experimental-block-pointer.py`.
This issue is to fix the functional issues with non-float16 dtype, e.g., int8, bfloat16, tf32.

---

Data type combinations of interest:

- [x] bf16_bf16_fp32
- [x] fp16_fp16_fp32
- [x] i8_i8_i32 #1155
- [x] tf32_tf32_f32 #1172 
- [ ] fp16_fp16_fp16 ~~#1211~~ #1258
- [ ] fp16_fp16_fp32_fp16 #1258 
- [ ] bf16_bf16_fp32_bf16 👉 #1264
- [ ] bf16_bf16_bf16 ~~#1213~~ 👉 #1265

**Comment by whitneywhtsang** [comment]
bfloat16 is handled in #1127, please continue investigation on the other dtypes.

**Comment by whitneywhtsang** [comment]
We can reference https://github.com/bashbaug/SimpleOpenCLSamples/tree/matrixperf/samples/99_matrixexperimentstf32 for tf32 support.
